### ISSUE TITLE
Allow appending files to an existing SQLite database

### ISSUE THREAD

**Issue by simonw** [simonw/csvs-to-sqlite#1]
Tool currently quits with an error if you try this.

Should it be possible to update existing tables with new data? Not sure about this. We certainly can’t handle schema changes. We would need to be told a column to treat as a “primary key”.

Given how cheap it is to recreate the database from scratch I’m inclined to say it’s not worth bothering with table updates.

**Comment by janimo** [comment]
Table updates are necessary if one wants to build a table from multiple separate CSV files. The alternative is merging the CSVs into a single file and passing that, but that fails for now for large files.

**Comment by simonw** [comment]
Yeah maybe having an optional --table option is the way to go here - the you can run the command saying "add the contents of these CSV file to that specific table, creating it if it does not exist"

**Comment by simonw** [comment]
I added the --table option in #10

**Comment by janimo** [comment]
This seems to work now.

**Comment by simonw** [comment]
#17 helped with this too: https://github.com/simonw/csvs-to-sqlite/commit/42ae631cbdeeb8ffce9135dde6651ff38b07a125
