### ISSUE TITLE
--shape option for specifying the "shape" of the resulting table

### ISSUE THREAD

**Issue by simonw** [simonw/csvs-to-sqlite#25]
This option will allow you to tell the command exactly what columns should be created in the new table and what their types should be.

For example:

    csvs-to-sqlite votes.csv votes.db --shape "county:Cty,votes:Vts(REAL)"

This will produce a table with just two columns: `Cty` and `Vts`. Those columns will correspond to the `county` and `votes` columns in the original CSV.

The `Cty` column will use the default type detected by pandas - but the `Vts` column will be forced to be a `REAL` column instead.

**Comment by simonw** [comment]
I'm not closing this yet because I'm not confident the new `--shape` option interacts well with other functionality such as `-c` - need to try it out against some real world CSV files and see how well it fairs. Also need better documentation for it.

**Comment by janimo** [comment]
It may be worth passing usecols to read_csv to skip reading the unused columns?

**Comment by simonw** [comment]
That's a great idea - I hadn't seen that option before. Will make that change.
