### ISSUE TITLE
csvs-to-sqlite has a hard requirement on package versions.

### ISSUE THREAD

**Issue by mratsim** [simonw/csvs-to-sqlite#37]
Currently version required is hardcoded:

https://github.com/simonw/csvs-to-sqlite/blob/dccbf65b37bc9eed50e9edb80a42f257e93edb1f/setup.py#L22-L28

The latest Pandas version is 0.21.0, this makes csvs-to-sqlite unusable with it by default and unusable with any package that requires the latest pandas.

Is there a reason why a specific version is enforced and not "0.20.3 or later"?

**Comment by simonw** [comment]
I've been installing csvs-to-sqlite into its own virtualenv and, since it's an application and not a library, I hadn't really considered the downsides of pinned dependencies.

I guess I could unpin them and set up Travis to run periodically so that any breaking changes cause a visible test failure.

**Comment by jw35** [comment]
An additional issue here is that the pinned version of Pandas, 0.20.3, doesn't seem to build against Python 3.7 (at least not the macOS Homebrew version). This is supported by the pandas documentation which suggests that only the latest version, 0.23.4, supports Python 3.7. 

This currently makes it impossible to install the as-distributed version of csvs-to-sqlite on a machine running Python 3.7.

**Comment by vitorio** [comment]
Was bit by this yesterday.  Running macOS High Sierra with stock Python 3.7 installed from python.org, pandas 0.20.3 won't successfully compile on it.  Had to git clone this repo, change the version in `setup.py` to 0.23.4 (latest), and then `pipenv install -e csvs-to-sqlite/`.

**Comment by simonw** [comment]
Fixed in #55 by dropping support for Python 2.x
