### ISSUE TITLE
Should accept URLs to CSV files as well as paths

### ISSUE THREAD

**Issue by simonw** [simonw/csvs-to-sqlite#4]
That way we can use this tool to suck one or more CSVs directly from the internet and turn them into a SQLite database.

    import pandas as pd
    pd.read_csv('https://raw.githubusercontent.com/openelections/openelections-data-ms/master/2013/20130205__ms__special__general__hinds__state_senate__28__precinct.csv')

This works already - so `pd.read_csv` is capable of this. We just need to teach the command-line option to accept URLs in addition to paths.

**Comment by simonw** [comment]
Relevant code is here:

https://github.com/simonw/csvs-to-sqlite/blob/e5263a53cce513bce7857c4e0f27aff769e0fe6d/csvs_to_sqlite/cli.py#L19-L24

Relevant documentation: http://click.pocoo.org/5/parameters/

**Comment by vettyvignesh** [comment]
Hi I am trying to learn about OSS. So can you assign me this issue?
