### ISSUE TITLE
Interpret all columns as TEXT data type

### ISSUE THREAD

**Issue by tsundara** [simonw/csvs-to-sqlite#42]
Is it possible to interpret all columns as TEXT datatype (through a flag maybe?)
I think the columns values are sampled and then column datatype is guessed. If there is an incompatible value in some row, then that row seems to be skipped. So instead, is it possible I load everything as TEXT data type? 
I just need the data in some format(for data comparison purposes), But all csv data must go into the table without skipping rows.

Thanks
Thyag

**Comment by ericlentz** [comment]
Similarly, I have item numbers in the format, 00645155909931 and it reads it as an integer datatype which converts it to 643169607033.

**Comment by tsibley** [comment]
I also have this issue. I thought specifying `--shape "csv_col:sql_col(text),…"` for each column would work, but the `text` type isn't passed into `pd.read_csv`'s `dtype` parameter.

**Comment by dannguyen** [comment]
It'd be great if there were an option akin to csvkit's `csvsql --no-inference` to force every column to be just `TEXT`, for imports in which there are just too many columns to easily specify the `--shape` flag:

https://csvkit.readthedocs.io/en/1.0.2/scripts/csvsql.html

**Comment by simonw** [comment]
This feature has now been released in csvs-to-sqlite 1.1
