### ISSUE TITLE
pandas version is pinned at less than current release

### ISSUE THREAD

**Issue by psychemedia** [simonw/csvs-to-sqlite#52]
The `setup.py` pins the version of *pandas* to a version that is behind the current release.

Click is also installed at a version that breaks datasette, which presumably requires a later version.

**Comment by simonw** [comment]
Click 6 was the last version to support Python 2.x, and csvs-to-sqlite currently works with that version of Python.

I'm inclined to drop 2.x support completely now, and tell users that if they need 2.x they can install a previous version.

**Comment by simonw** [comment]
Looks like Pandas 0.25.0 doesn't support Python 3.x either.
