### ISSUE TITLE
-d flag creates column as TEXT

### ISSUE THREAD

**Issue by andy47** [simonw/csvs-to-sqlite#65]
I'm using the -d flag on a column that contains iso formatted dates (e.g. '2020-07-02') in my csv file, but when this is converted to a sqlite database the column is created as a TEXT. I'm using a tool (metabase) that reads the schema metadata so I'd like this column created as a DATE datatype if possible. Is there a way to force this?

**Comment by simonw** [comment]
SQLite technically only supports these column types: https://sqlite.org/datatype3.html#storage_classes_and_datatypes

- NULL
- INTEGER
- REAL
- TEXT
- BLOB

You can put `date` in a `create table` statement but the underlying column will be created as a `NUMERIC` - according to this table: https://www.sqlite.org/datatype3.html#affinity_name_examples

If you want different types my suggestion would be to manually run a `CREATE TABLE ...` command with the types that you want, then run `INSERT INTO new_table SELECT * FROM old_table` to populate it. I think supporting cosmetic types is out of scope for this particular tool - though I might add something to `sqlite-utils` for that some day in the future as that tool continues to expand.
