### ISSUE TITLE
outdated pandas dependency in setup.py?

### ISSUE THREAD

**Issue by rtanglao** [simonw/csvs-to-sqlite#73]
[setup.py](https://github.com/simonw/csvs-to-sqlite/blob/master/setup.py#L28) seems to have an old version of pandas. Should the pandas dependency be on some pandas version that is more recent or remove the version altogether i.e. change `pandas~=0.25.0` to just `pandas`?

**Comment by simonw** [comment]
Good call - I should definitely bump this to supporting the most recent Pandas.

**Comment by simonw** [comment]
Fixed.
